### PR TITLE
Catch "No field with type net.minecraft.server.v1_15_R1.DataWatcher e…

### LINKED ISSUE #13: Unable to change player name with 1.15.1
This exception is thrown if `changePlayerName`  or `updatePlayer` is executed

```
org.bukkit.command.CommandException: Unhandled exception executing 'changeidentity:changeidentity peter_roelle' in de.simonit.changeidentity.commands.ChangeIdentityCommand(changeidentity)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[craftbukkit-1.15.1-R0.1-SNAPSHOT.jar:git-Bukkit-2d9db47]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:690) ~[craftbukkit-1.15.1-R0.1-SNAPSHOT.jar:git-Bukkit-2d9db47]
	at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1606) ~[craftbukkit-1.15.1-R0.1-SNAPSHOT.jar:git-Bukkit-2d9db47]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1460) ~[craftbukkit-1.15.1-R0.1-SNAPSHOT.jar:git-Bukkit-2d9db47]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(SourceFile:36) ~[craftbukkit-1.15.1-R0.1-SNAPSHOT.jar:git-Bukkit-2d9db47]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(SourceFile:9) ~[craftbukkit-1.15.1-R0.1-SNAPSHOT.jar:git-Bukkit-2d9db47]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[craftbukkit-1.15.1-R0.1-SNAPSHOT.jar:git-Bukkit-2d9db47]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [craftbukkit-1.15.1-R0.1-SNAPSHOT.jar:git-Bukkit-2d9db47]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [craftbukkit-1.15.1-R0.1-SNAPSHOT.jar:git-Bukkit-2d9db47]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [craftbukkit-1.15.1-R0.1-SNAPSHOT.jar:git-Bukkit-2d9db47]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [craftbukkit-1.15.1-R0.1-SNAPSHOT.jar:git-Bukkit-2d9db47]
	at net.minecraft.server.v1_15_R1.MinecraftServer.aZ(MinecraftServer.java:875) [craftbukkit-1.15.1-R0.1-SNAPSHOT.jar:git-Bukkit-2d9db47]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:868) [craftbukkit-1.15.1-R0.1-SNAPSHOT.jar:git-Bukkit-2d9db47]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [craftbukkit-1.15.1-R0.1-SNAPSHOT.jar:git-Bukkit-2d9db47]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:852) [craftbukkit-1.15.1-R0.1-SNAPSHOT.jar:git-Bukkit-2d9db47]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:792) [craftbukkit-1.15.1-R0.1-SNAPSHOT.jar:git-Bukkit-2d9db47]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: com.comphenix.protocol.reflect.FieldAccessException: No field with type net.minecraft.server.v1_15_R1.DataWatcher exists in class PacketPlayOutNamedEntitySpawn.
	at com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:363) ~[?:?]
	at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:343) ~[?:?]
	at com.bringholm.nametagchanger.ProtocolLibPacketHandler.sendNamedEntitySpawnPacket(ProtocolLibPacketHandler.java:140) ~[?:?]
	at com.bringholm.nametagchanger.NameTagChanger.updatePlayer(NameTagChanger.java:283) ~[?:?]
	at com.bringholm.nametagchanger.NameTagChanger.changePlayerName(NameTagChanger.java:152) ~[?:?]
	at de.simonit.changeidentity.commands.ChangeIdentityCommand.execute(ChangeIdentityCommand.java:53) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[craftbukkit-1.15.1-R0.1-SNAPSHOT.jar:git-Bukkit-2d9db47]
	... 16 more
```
@Alvin-LB

### PR DESCRIPTION
**Pull request by SimonIT**
…xists in class PacketPlayOutSpawnEntityLiving", fixes #13

### CODE REVIEW

**Comment by Alvin-LB** [comment]
Hi. I don't believe this will fix anything since it just catches the exception. Have you verified that this solution works?

This project needs proper updates and verifications for a number of versions (which I haven't done). If you are willing to try and do that, then feel free to, but I don't feel a solution like this will achieve anything.

**Comment by SimonIT** [comment]
Yes this fixed it for me. The label above the player and the skin got changed

**Comment by Alvin-LB** [comment]
Yes, I understand that it probably did, and feel free to use this workaround by yourself.
The DataWatcher used to handle a bunch of subtle properties (like the glowing effect if memory serves me), and I have to make sure that these things are taken care of (I seriously doubt that everything works if you just catch the exception silently).

**Comment by SimonIT** [comment]
That's possible. I thought it's a good idea to share this quick and dirty workaround. I think a half working lib is better than a not working one ;)
I tried to fix it as you can see [here](https://github.com/SimonIT/NameTagChanger/commit/f252353c59f670a574de19fef4783790b290549e) with sending an extra packet with this data as advised, but failed with the same exception

**Comment by Alvin-LB** [comment]
Okay. How about this:
I will have a look at this within the coming week. If I can solve it properly I will do so, otherwise, I will merge your PR.

**Comment by SimonIT** [comment]
Thank you, I appreciate your help

**Comment by SimonIT** [comment]
So what going to happen?

**Comment by SimonIT** [comment]
@Alvin-LB Hm?

**Pull request closed without merging**
